export function logTest() {
	return [
		{
			firstname: 'abc1',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc1@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc2',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc2@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc3',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc3@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc4',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc4@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc5',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc5@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc6',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc6@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc7',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc7@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc8',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc8@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc9',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc9@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc10',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc10@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc11',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc11@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc12',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc12@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc13',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc13@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc14',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc14@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc15',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc15@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc16',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc16@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc17',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc17@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc18',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc18@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc19',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc19@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc111',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc111@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc122',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc122@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc133',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc133@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc144',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc144@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc155',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc155@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc166',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc166@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc177',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc177@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc188',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc188@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc199',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc199@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc121',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc121@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc123',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc123@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc124',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc124@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc125',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc125@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc126',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc126@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc127',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc127@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc128',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc128@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc129',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc129@gmail.com',
			isPayed:true,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc131',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc131@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc132',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc132@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc133',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc133@gmail.com',
			isPayed:true,
			isActive:true,
			fee:2000,
			isFaculty:false
		},{
			firstname: 'abc134',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc134@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc135',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc135@gmail.com',
			isPayed:true,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc136',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc136@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc137',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc137@gmail.com',
			isPayed:true,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc138',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc138@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc139',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc139@gmail.com',
			isPayed:false,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc140',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc140@gmail.com',
			isPayed:true,
			isActive:true,
			fee:2000,
			isFaculty:false
		},
		{
			firstname: 'abc141',
			lastname:'xyz',
			phone: 9123456789,
			age: 9,
			address: 'kkd',
			class: '3rd class',
			gmail:'abc141@gmail.com',
			isPayed:false,
			isActive:false,
			fee:2500,
			isFaculty:false
		},
	]
}